services:
  - type: web
    name: tg-bot-bpgu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: STAROSTA_TELEGRAM_ID
        value: "1131010316"
      - key: TIMEZONE
        value: "Europe/Minsk"
      - key: APP_ENV
        value: "production"
      - key: PORT
        value: "8000"
      - key: HOST
        value: "0.0.0.0"
      - key: FRONTEND_URL
        value: "*"
