"""
RFC 7807 Problem Details schema for error responses.
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ProblemDetail(BaseModel):
    """
    Standard RFC 7807 Problem Details structure.
    https://datatracker.ietf.org/doc/html/rfc7807
    """
    type: str = Field(
        default="about:blank",
        description="URI reference that identifies the problem type.",
    )
    title: str = Field(
        ...,
        description="Short, human-readable summary of the problem type.",
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server.",
    )
    detail: Optional[str] = Field(
        None,
        description="Human-readable explanation specific to this occurrence of the problem.",
    )
    instance: Optional[str] = Field(
        None,
        description="URI reference that identifies the specific occurrence of the problem.",
    )
    data: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured contextual metadata associated with the error.",
    )
    invalid_params: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Validation errors breakdown for 422 Unprocessable Entity responses.",
    )
